@extends('frontend.layouts.app')
<!-- Dynamic Tiltile  -->
@section('title', 'Ask a Free Question')
@section('meta_description', 'Join Now to File Company HR Documents Online with the help of kanoonvala.com; Hire the top lawyers to assist you draft a Company HR Documents.')
@section('meta_keywords', 'File Company HR Documents Online, Company HR Documents, Human Resources Document')
<!-- Page Content -->
@section('content')
    <div class="section-empty no-paddings">
        <div class="section-slider row-8 white">
            <div class="flexslider advanced-slider slider visible-dir-nav" data-options="animation:fade">
                <ul class="slides">
                    <li data-slider-anima="fade-left" data-time="1000">
                        <div class="section-slide">
                            <div class="bg-cover"
                                 style="background-image:url({!! asset('assets/images/slide1.jpg') !!})"></div>
                            <div class="container">
                                <div class="container-middle">
                                    <div class="container-inner text-center">
                                        <div class="col-md-8 col-md-offset-2">
                                            <div class="row">
                                                <div class="col-md-12 anima">
                                                    <h1 class="text-white text-l heading_one">Join Now to ask a free
                                                        question</h1>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="section-empty">
        <div class="container content">
            <div class="main-content-area">
                <section class="custom-padding" id="how-it-work" style="background:#fff;">
                    <div class="container">
                        <div class="row">
                            <form class="form_box" action="{{route('frontend.freeQuestion.save')}}" method="post"
                                  role="form">
                                @csrf
                                <h2 class="text-center profile-hide">Ask a Free Legal Question Online</h2>
                                <div class="row">
                                    <div class="col-md-12 form-group">
                                        <label>Select Area of Law</label>
                                        <select class="form-control" name="area" required>
                                            <option value="145">Anticipatory Bail</option>
                                            <option value="37" class="option selected">Arbitration</option>
                                            <option value="136">Armed Forces Tribunal</option>
                                            <option value="139">Banking / Finance</option>
                                            <option value="147">Bankruptcy / Insolvency</option>
                                            <option value="143">Breach of Contract</option>
                                            <option value="38">Cheque Bounce</option>
                                            <option value="133">Child Custody</option>
                                            <option value="138">Civil</option>
                                            <option value="39">Consumer Court</option>
                                            <option value="126">Corporate</option>
                                            <option value="41">Criminal</option>
                                            <option value="42">Customs &amp; Central Excise</option>
                                            <option value="43">Cyber Crime</option>
                                            <option value="44">Divorce</option>
                                            <option value="45">Documentation</option>
                                            <option value="141">Domestic Violence</option>
                                            <option value="46">Family</option>
                                            <option value="140">GST</option>
                                            <option value="47">Immigration</option>
                                            <option value="49">Insurance</option>
                                            <option value="51">International Law</option>
                                            <option value="53">Labour &amp; Service</option>
                                            <option value="54">Landlord/Tenant</option>
                                            <option value="149">Media and Entertainment</option>
                                            <option value="55">Medical Negligence</option>
                                            <option value="56">Motor Accident</option>
                                            <option value="135">Muslim Law</option>
                                            <option value="146">NCLT</option>
                                            <option value="148">Patent</option>
                                            <option value="57">Property</option>
                                            <option value="58">R.T.I</option>
                                            <option value="59">Recovery</option>
                                            <option value="142">RERA</option>
                                            <option value="50">Startup</option>
                                            <option value="144">Succession Certificate</option>
                                            <option value="137">Supreme Court</option>
                                            <option value="60">Tax</option>
                                            <option value="40">Trademark &amp; Copyright</option>
                                            <option value="61">Wills / Trusts</option>
                                        </select>
                                    </div>
                                    <div class="col-md-12 form-group">
                                        <label>Select City</label>
                                        <select class="form-control" name="city" required>
                                            <option id="162">Delhi</option>
                                            <option id="469">Mumbai</option>
                                            <option id="298">Bangalore</option>
                                            <option id="625">Chennai</option>
                                            <option id="238">Gurgaon</option>
                                            <option id="784">Noida</option>
                                            <option id="236">Faridabad</option>
                                            <option id="740">Ghaziabad</option>
                                            <option id="614">Aarani</option>
                                            <option id="534">Abohar</option>
                                            <option id="967">Abu Road</option>
                                            <option id="425">Achalpur</option>
                                            <option id="2">Adilabad</option>
                                            <option id="273">Adityapur</option>
                                            <option id="3">Adoni</option>
                                            <option id="692">Agartala</option>
                                            <option id="703">Agra</option>
                                            <option id="167">Ahmedabad</option>
                                            <option id="426">Ahmednagar</option>
                                            <option id="506">Aizawl</option>
                                            <option id="567">Ajmer</option>
                                            <option id="991">Akbarpur</option>
                                            <option id="427">Akola</option>
                                            <option id="428">Akot</option>
                                            <option id="347">Alappuzha</option>
                                            <option id="704">Aligarh</option>
                                            <option id="811">Alipurduar</option>
                                            <option id="705">Allahabad</option>
                                            <option id="693">Almora</option>
                                            <option id="568">Alwar</option>
                                            <option id="4">Amalapuram</option>
                                            <option id="429">Amalner</option>
                                            <option id="430">Ambajogai</option>
                                            <option id="232">Ambala</option>
                                            <option id="233">AmbalaSadar</option>
                                            <option id="615">Ambasamudram</option>
                                            <option id="144">Ambikapur</option>
                                            <option id="616">Ambur</option>
                                            <option id="431">Amravati</option>
                                            <option id="168">Amreli</option>
                                            <option id="535">Amritsar</option>
                                            <option id="706">Amroha</option>
                                            <option id="5">Anakapalle</option>
                                            <option id="169">Anand</option>
                                            <option id="954">Anandpur Sahib</option>
                                            <option id="6">Anantapur</option>
                                            <option id="265">Anantnag</option>
                                            <option id="432">Anjangaon</option>
                                            <option id="170">Anjar</option>
                                            <option id="171">Ankleshwar</option>
                                            <option id="617">Arakkonam</option>
                                            <option id="812">Arambag</option>
                                            <option id="109">Araria</option>
                                            <option id="618">Arcot</option>
                                            <option id="110">Arrah</option>
                                            <option id="619">Aruppukkottai</option>
                                            <option id="813">Asansol</option>
                                            <option id="374">Ashoknagar</option>
                                            <option id="814">AshoknagarKalyangarh</option>
                                            <option id="620">Attur</option>
                                            <option id="707">Auraiya</option>
                                            <option id="989">Aurangabad - Bihar</option>
                                            <option id="433">Aurangabad - Maharashtra</option>
                                            <option id="985">Australia</option>
                                            <option id="621">Avaniapuram</option>
                                            <option id="708">Azamgarh</option>
                                            <option id="434">Badlapur</option>
                                            <option id="111">Bagaha</option>
                                            <option id="297">Bagalkot</option>
                                            <option id="274">Bagbera</option>
                                            <option id="234">Bahadurgarh</option>
                                            <option id="815">Baharampur</option>
                                            <option id="709">Baheri</option>
                                            <option id="710">Bahraich</option>
                                            <option id="816">Baidyabati</option>
                                            <option id="375">Balaghat</option>
                                            <option id="509">Balangir</option>
                                            <option id="510">Balasore</option>
                                            <option id="435">Ballarpur</option>
                                            <option id="711">Ballia</option>
                                            <option id="817">Bally</option>
                                            <option id="569">Balotra</option>
                                            <option id="712">Balrampur</option>
                                            <option id="818">Balurghat</option>
                                            <option id="713">Banda</option>
                                            <option id="819">Bankura</option>
                                            <option id="820">Bansberia</option>
                                            <option id="570">Banswara</option>
                                            <option id="7">Bapatla</option>
                                            <option id="714">Barabanki</option>
                                            <option id="436">Baramati</option>
                                            <option id="266">Baramulla</option>
                                            <option id="571">Baran</option>
                                            <option id="821">Baranagar</option>
                                            <option id="822">Barasat</option>
                                            <option id="715">Baraut</option>
                                            <option id="511">Barbil</option>
                                            <option id="823">Bardhaman</option>
                                            <option id="172">Bardoli</option>
                                            <option id="716">Bareilly</option>
                                            <option id="512">Bargarh</option>
                                            <option id="572">Bari</option>
                                            <option id="513">Baripada</option>
                                            <option id="573">Barmer</option>
                                            <option id="536">Barnala</option>
                                            <option id="824">Barrackpore</option>
                                            <option id="437">Barshi</option>
                                            <option id="825">Baruipur</option>
                                            <option id="299">Basavakalyan</option>
                                            <option id="826">Basirhat</option>
                                            <option id="438">Basmath</option>
                                            <option id="717">Basti</option>
                                            <option id="537">Batala</option>
                                            <option id="538">Bathinda</option>
                                            <option id="574">Beawar</option>
                                            <option id="439">Beed</option>
                                            <option id="112">Begusarai</option>
                                            <option id="718">BehtaHajipur</option>
                                            <option id="719">Bela Pratapgarh</option>
                                            <option id="827">Beldanga</option>
                                            <option id="300">Belgaum</option>
                                            <option id="8">Bellampalle</option>
                                            <option id="301">Bellary</option>
                                            <option id="113">Bettiah</option>
                                            <option id="376">Betul</option>
                                            <option id="984">Bhabua</option>
                                            <option id="720">Bhadohi</option>
                                            <option id="514">Bhadrak</option>
                                            <option id="302">Bhadravathi</option>
                                            <option id="440">Bhadravati</option>
                                            <option id="828">Bhadreswar</option>
                                            <option id="114">Bhagalpur</option>
                                            <option id="441">Bhandara</option>
                                            <option id="575">Bharatpur</option>
                                            <option id="173">Bharuch</option>
                                            <option id="145">Bhatapara</option>
                                            <option id="929">Bhatinda</option>
                                            <option id="829">Bhatpara</option>
                                            <option id="622">Bhavani</option>
                                            <option id="174">Bhavnagar</option>
                                            <option id="515">Bhawanipatna</option>
                                            <option id="146">Bhilai</option>
                                            <option id="147">BhilaiCharoda</option>
                                            <option id="576">Bhilwara</option>
                                            <option id="9">Bhimavaram</option>
                                            <option id="377">Bhind</option>
                                            <option id="235">Bhiwani</option>
                                            <option id="378">Bhopal</option>
                                            <option id="516">Bhubaneswar</option>
                                            <option id="175">Bhuj</option>
                                            <option id="275">Bhuli</option>
                                            <option id="442">Bhusawal</option>
                                            <option id="303">Bidar</option>
                                            <option id="830">Bidhannagar</option>
                                            <option id="304">Bijapur</option>
                                            <option id="721">Bijnor</option>
                                            <option id="577">Bikaner</option>
                                            <option id="148">Bilaspur</option>
                                            <option id="176">Bilimora</option>
                                            <option id="379">BinaEtawa</option>
                                            <option id="831">Birnagar</option>
                                            <option id="722">Bisalpur</option>
                                            <option id="832">Bishnupur</option>
                                            <option id="10">Bobbili</option>
                                            <option id="11">Bodhan</option>
                                            <option id="623">Bodinayakkanur</option>
                                            <option id="276">BokaroSteelCity</option>
                                            <option id="833">BolpurSantiniketan</option>
                                            <option id="94">Bongaigaon</option>
                                            <option id="834">Bongaon</option>
                                            <option id="177">Borsad</option>
                                            <option id="178">Botad</option>
                                            <option id="517">Brahmapur</option>
                                            <option id="518">Brajarajnagar</option>
                                            <option id="723">Budaun</option>
                                            <option id="835">BudgeBudge</option>
                                            <option id="724">Bulandshahr</option>
                                            <option id="443">Buldhana</option>
                                            <option id="578">Bundi</option>
                                            <option id="380">Burhanpur</option>
                                            <option id="115">Buxar</option>
                                            <option id="277">Chaibasa</option>
                                            <option id="836">Chakdaha</option>
                                            <option id="278">Chakradharpur</option>
                                            <option id="444">Chalisgaon</option>
                                            <option id="837">Champdani</option>
                                            <option id="305">Chamrajnagar</option>
                                            <option id="838">Chandannagar</option>
                                            <option id="725">Chandausi</option>
                                            <option id="143">Chandigarh</option>
                                            <option id="179">Chandkheda</option>
                                            <option id="180">Chandlodiya</option>
                                            <option id="726">Chandpur</option>
                                            <option id="445">Chandrapur</option>
                                            <option id="839">Chandrokona</option>
                                            <option id="348">Changanacherry</option>
                                            <option id="306">Channapatna</option>
                                            <option id="116">Chapra</option>
                                            <option id="952">Charkhi Dadri</option>
                                            <option id="959">Chatrapur</option>
                                            <option id="624">Chengalpattu</option>
                                            <option id="349">Cherthala</option>
                                            <option id="381">Chhatarpur</option>
                                            <option id="727">Chhibramau</option>
                                            <option id="382">Chhindwara</option>
                                            <option id="626">Chidambaram</option>
                                            <option id="307">Chikkaballapur</option>
                                            <option id="930">Chikkadpally</option>
                                            <option id="308">Chikmagalur</option>
                                            <option id="982">Chikodi</option>
                                            <option id="12">Chilakalurupet</option>
                                            <option id="13">Chinnachowk</option>
                                            <option id="309">Chintamani</option>
                                            <option id="14">Chirala</option>
                                            <option id="279">Chirkunda</option>
                                            <option id="149">Chirmiri</option>
                                            <option id="310">Chitradurga</option>
                                            <option id="15">Chittoor</option>
                                            <option id="579">Chittorgarh</option>
                                            <option id="350">Chittur</option>
                                            <option id="580">Chomu</option>
                                            <option id="446">Chopda</option>
                                            <option id="581">Churu</option>
                                            <option id="627">Coimbatore</option>
                                            <option id="840">Contai</option>
                                            <option id="841">CoochBehar</option>
                                            <option id="628">Coonoor</option>
                                            <option id="842">CoopersCamp</option>
                                            <option id="629">Cuddalore</option>
                                            <option id="16">Cuddapah</option>
                                            <option id="519">Cuttack</option>
                                            <option id="181">Dabhoi</option>
                                            <option id="383">Dabra</option>
                                            <option id="728">Dadri</option>
                                            <option id="182">Dahod</option>
                                            <option id="843">Dainhat</option>
                                            <option id="260">Dalhousie</option>
                                            <option id="844">Dalkhola</option>
                                            <option id="150">DalliRajhara</option>
                                            <option id="280">Daltonganj</option>
                                            <option id="160">Daman</option>
                                            <option id="384">Damoh</option>
                                            <option id="311">Dandeli</option>
                                            <option id="117">Darbhanga</option>
                                            <option id="845">Darjeeling</option>
                                            <option id="385">Datia</option>
                                            <option id="582">Dausa</option>
                                            <option id="312">Davanagere</option>
                                            <option id="183">Deesa</option>
                                            <option id="694">Dehradun</option>
                                            <option id="118">DehrionSone</option>
                                            <option id="729">Deoband</option>
                                            <option id="281">Deoghar</option>
                                            <option id="447">Deolali</option>
                                            <option id="730">Deoria</option>
                                            <option id="630">Devarshola</option>
                                            <option id="386">Dewas</option>
                                            <option id="151">Dhamtari</option>
                                            <option id="282">Dhanbad</option>
                                            <option id="387">Dhanpuri</option>
                                            <option id="388">Dhar</option>
                                            <option id="986">Dharamgarh</option>
                                            <option id="261">Dharamsala</option>
                                            <option id="631">Dharapuram</option>
                                            <option id="632">Dharmapuri</option>
                                            <option id="17">Dharmavaram</option>
                                            <option id="992">Dharwad</option>
                                            <option id="520">Dhenkanal</option>
                                            <option id="184">Dholka</option>
                                            <option id="583">Dholpur</option>
                                            <option id="185">Dhoraji</option>
                                            <option id="186">Dhrangadhra</option>
                                            <option id="95">Dhubri</option>
                                            <option id="448">Dhule</option>
                                            <option id="846">Dhulian</option>
                                            <option id="847">Dhupguri</option>
                                            <option id="848">DiamondHarbour</option>
                                            <option id="96">Dibrugarh</option>
                                            <option id="507">Dimapur</option>
                                            <option id="119">DinapurNizamat</option>
                                            <option id="633">Dindigul</option>
                                            <option id="97">Diphu</option>
                                            <option id="98">Dispur</option>
                                            <option id="161">Diu</option>
                                            <option id="313">Doddaballapur</option>
                                            <option id="976">Dombivli</option>
                                            <option id="933">Dubai</option>
                                            <option id="849">Dubrajpur</option>
                                            <option id="850">Dumdum</option>
                                            <option id="964">Dumka</option>
                                            <option id="152">Durg</option>
                                            <option id="851">Durgapur</option>
                                            <option id="187">Dwarka-Gujarat</option>
                                            <option id="978">East Godavari</option>
                                            <option id="351">Edathala</option>
                                            <option id="852">Egra</option>
                                            <option id="18">Eluru</option>
                                            <option id="853">EnglishBazar</option>
                                            <option id="940">Ernakulam</option>
                                            <option id="634">Erode</option>
                                            <option id="731">Etah</option>
                                            <option id="732">Etawah</option>
                                            <option id="733">Faizabad</option>
                                            <option id="539">Faridkot</option>
                                            <option id="734">Faridpur</option>
                                            <option id="735">Farrukhabad</option>
                                            <option id="237">Fatehabad</option>
                                            <option id="937">Fatehgarh Sahib</option>
                                            <option id="736">Fatehpur</option>
                                            <option id="540">Fazilka</option>
                                            <option id="737">Firozabad</option>
                                            <option id="541">Firozpur</option>
                                            <option id="542">FirozpurCantonment</option>
                                            <option id="314">Gadag</option>
                                            <option id="19">GaddiAnnaram</option>
                                            <option id="20">Gadwal</option>
                                            <option id="188">Gandhidham</option>
                                            <option id="189">Gandhinagar</option>
                                            <option id="738">Gangaghat</option>
                                            <option id="584">Ganganagar</option>
                                            <option id="585">GangapurCity</option>
                                            <option id="854">Gangarampur</option>
                                            <option id="315">Gangavathi</option>
                                            <option id="739">Gangoh</option>
                                            <option id="613">Gangtok</option>
                                            <option id="979">Ganjam</option>
                                            <option id="855">Garulia</option>
                                            <option id="120">Gaya</option>
                                            <option id="856">Ghatal</option>
                                            <option id="190">Ghatlodiya</option>
                                            <option id="741">Ghazipur</option>
                                            <option id="283">Giridih</option>
                                            <option id="163">Goa</option>
                                            <option id="857">Gobardanga</option>
                                            <option id="635">Gobichettipalayam</option>
                                            <option id="191">Godhra</option>
                                            <option id="316">Gokak</option>
                                            <option id="742">GolaGokarannath</option>
                                            <option id="743">Gonda</option>
                                            <option id="192">Gondal</option>
                                            <option id="449">Gondia</option>
                                            <option id="121">Gopalganj</option>
                                            <option id="744">Gorakhpur</option>
                                            <option id="745">Greater Noida</option>
                                            <option id="21">Gudivada</option>
                                            <option id="636">Gudiyatham</option>
                                            <option id="22">Gudur</option>
                                            <option id="317">Gulbarga</option>
                                            <option id="974">Gumla</option>
                                            <option id="389">Guna</option>
                                            <option id="23">Guntakal</option>
                                            <option id="24">Guntur</option>
                                            <option id="543">Gurdaspur</option>
                                            <option id="858">Guskara</option>
                                            <option id="99">Guwahati</option>
                                            <option id="390">Gwalior</option>
                                            <option id="859">Habra</option>
                                            <option id="122">Hajipur</option>
                                            <option id="860">Haldia</option>
                                            <option id="861">Haldibari</option>
                                            <option id="695">Haldwani</option>
                                            <option id="862">Halisahar</option>
                                            <option id="990">Hamirpur</option>
                                            <option id="932">Hamirpur - Himachal Pradesh</option>
                                            <option id="239">Hansi</option>
                                            <option id="586">Hanumangarh</option>
                                            <option id="746">Hapur</option>
                                            <option id="391">Harda</option>
                                            <option id="747">Hardoi</option>
                                            <option id="696">Haridwar</option>
                                            <option id="318">Harihar</option>
                                            <option id="748">Hasanpur</option>
                                            <option id="319">Hassan</option>
                                            <option id="749">Hathras</option>
                                            <option id="320">Haveri</option>
                                            <option id="284">Hazaribag</option>
                                            <option id="193">Himatnagar</option>
                                            <option id="587">Hindaun</option>
                                            <option id="25">Hindupur</option>
                                            <option id="450">Hinganghat</option>
                                            <option id="451">Hingoli</option>
                                            <option id="240">Hisar</option>
                                            <option id="392">Hoshangabad</option>
                                            <option id="544">Hoshiarpur</option>
                                            <option id="321">Hospet</option>
                                            <option id="637">Hosur</option>
                                            <option id="863">Howrah</option>
                                            <option id="322">Hubli</option>
                                            <option id="864">HugliChuchura</option>
                                            <option id="26">Hyderabad</option>
                                            <option id="452">Ichalkaranji</option>
                                            <option id="323">Ilkal</option>
                                            <option id="503">Imphal</option>
                                            <option id="393">Indore</option>
                                            <option id="865">Islampur</option>
                                            <option id="93">Itanagar</option>
                                            <option id="394">Itarsi</option>
                                            <option id="395">Jabalpur</option>
                                            <option id="241">Jagadhri</option>
                                            <option id="958">Jagatsinghpur</option>
                                            <option id="153">Jagdalpur</option>
                                            <option id="545">Jagraon</option>
                                            <option id="27">Jagtial</option>
                                            <option id="750">Jahangirabad</option>
                                            <option id="588">Jaipur</option>
                                            <option id="589">Jaisalmer</option>
                                            <option id="751">Jalalpur</option>
                                            <option id="546">Jalandhar</option>
                                            <option id="453">Jalgaon</option>
                                            <option id="454">Jalna</option>
                                            <option id="866">Jalpaiguri</option>
                                            <option id="324">Jamakhandi</option>
                                            <option id="123">Jamalpur</option>
                                            <option id="267">Jammu</option>
                                            <option id="194">Jamnagar</option>
                                            <option id="285">Jamshedpur</option>
                                            <option id="124">Jamui</option>
                                            <option id="867">Jamuria</option>
                                            <option id="396">Jaora</option>
                                            <option id="521">Jatani</option>
                                            <option id="752">Jaunpur</option>
                                            <option id="980">Jawali</option>
                                            <option id="868">JaynagarMazilpur</option>
                                            <option id="125">Jehanabad</option>
                                            <option id="195">Jetpur</option>
                                            <option id="522">Jeypore</option>
                                            <option id="242">Jhajjar</option>
                                            <option id="869">Jhalda</option>
                                            <option id="753">Jhansi</option>
                                            <option id="870">Jhargram</option>
                                            <option id="286">Jharia</option>
                                            <option id="523">Jharsuguda</option>
                                            <option id="287">JhumriTelaiya</option>
                                            <option id="590">Jhunjhunu</option>
                                            <option id="871">JiaganjAzimganj</option>
                                            <option id="243">Jind</option>
                                            <option id="591">Jodhpur</option>
                                            <option id="288">Jorapokhar</option>
                                            <option id="100">Jorhat</option>
                                            <option id="196">Junagadh</option>
                                            <option id="638">Kadayanallur</option>
                                            <option id="197">Kadi</option>
                                            <option id="28">Kadiri</option>
                                            <option id="29">Kagaznagar</option>
                                            <option id="754">Kairana</option>
                                            <option id="244">Kaithal</option>
                                            <option id="30">Kakinada</option>
                                            <option id="872">Kaliaganj</option>
                                            <option id="873">Kalimpong</option>
                                            <option id="31">Kallur</option>
                                            <option id="874">Kalna</option>
                                            <option id="198">Kalol</option>
                                            <option id="455">Kalyan</option>
                                            <option id="875">Kalyani</option>
                                            <option id="876">Kamarhati</option>
                                            <option id="639">Kambam</option>
                                            <option id="456">Kamthi</option>
                                            <option id="640">Kanchipuram</option>
                                            <option id="877">Kanchrapara</option>
                                            <option id="878">Kandi</option>
                                            <option id="199">Kandla</option>
                                            <option id="352">Kanhangad</option>
                                            <option id="755">Kannauj</option>
                                            <option id="353">Kannur</option>
                                            <option id="756">Kanpur</option>
                                            <option id="641">Kanyakumari</option>
                                            <option id="961">Kapasan</option>
                                            <option id="32">Kapra</option>
                                            <option id="547">Kapurthala</option>
                                            <option id="457">Karad</option>
                                            <option id="531">Karaikal</option>
                                            <option id="642">Karaikudi</option>
                                            <option id="458">Karanja</option>
                                            <option id="592">Karauli</option>
                                            <option id="101">Karimganj</option>
                                            <option id="33">Karimnagar</option>
                                            <option id="245">Karnal</option>
                                            <option id="643">Karur</option>
                                            <option id="325">Karwar</option>
                                            <option id="354">Kasaragod</option>
                                            <option id="757">Kasganj</option>
                                            <option id="697">Kashipur</option>
                                            <option id="268">Kathua</option>
                                            <option id="126">Katihar</option>
                                            <option id="397">Katni</option>
                                            <option id="289">Katras</option>
                                            <option id="879">Katwa</option>
                                            <option id="34">Kavali</option>
                                            <option id="373">Kavaratti</option>
                                            <option id="355">Kayamkulam</option>
                                            <option id="524">Kendujhar</option>
                                            <option id="200">Keshod</option>
                                            <option id="201">Khambhat</option>
                                            <option id="459">Khamgaon</option>
                                            <option id="35">Khammam</option>
                                            <option id="398">Khandwa</option>
                                            <option id="548">Khanna</option>
                                            <option id="154">Kharagpur</option>
                                            <option id="880">Kharar</option>
                                            <option id="881">Khardaha</option>
                                            <option id="399">Khargone</option>
                                            <option id="758">Khatauli</option>
                                            <option id="971">Khekada</option>
                                            <option id="882">Khirpai</option>
                                            <option id="460">Khopoli</option>
                                            <option id="759">Khurja</option>
                                            <option id="760">Kiratpur</option>
                                            <option id="127">Kishanganj</option>
                                            <option id="593">Kishangarh</option>
                                            <option id="356">Kochi</option>
                                            <option id="508">Kohima</option>
                                            <option id="326">Kolar</option>
                                            <option id="461">Kolhapur</option>
                                            <option id="883">Kolkata</option>
                                            <option id="357">Kollam</option>
                                            <option id="327">Kollegal</option>
                                            <option id="644">Komarapalayam</option>
                                            <option id="761">Konch</option>
                                            <option id="884">Konnagar</option>
                                            <option id="462">Kopargaon</option>
                                            <option id="328">Koppal</option>
                                            <option id="36">Koratla</option>
                                            <option id="155">Korba</option>
                                            <option id="594">Kota</option>
                                            <option id="549">Kotkapura</option>
                                            <option id="931">Kotputli</option>
                                            <option id="37">Kottagudem</option>
                                            <option id="358">Kottayam</option>
                                            <option id="944">Kottur</option>
                                            <option id="645">Kovilpatti</option>
                                            <option id="359">Kozhikode</option>
                                            <option id="646">Krishnagiri</option>
                                            <option id="885">Krishnanagar</option>
                                            <option id="595">Kuchaman</option>
                                            <option id="262">Kullu</option>
                                            <option id="886">Kulti</option>
                                            <option id="647">Kumbakonam</option>
                                            <option id="968">Kupwara</option>
                                            <option id="38">Kurnool</option>
                                            <option id="887">Kurseong</option>
                                            <option id="246">Kurukshetra</option>
                                            <option id="596">Ladnun</option>
                                            <option id="762">Laharpur</option>
                                            <option id="763">Lakhimpur</option>
                                            <option id="128">Lakhisarai</option>
                                            <option id="764">Lalitpur</option>
                                            <option id="463">Latur</option>
                                            <option id="269">Leh</option>
                                            <option id="464">Lonavla</option>
                                            <option id="927">London-UK</option>
                                            <option id="765">Loni</option>
                                            <option id="766">Lucknow</option>
                                            <option id="550">Ludhiana</option>
                                            <option id="102">Lumding</option>
                                            <option id="39">Machilipatnam</option>
                                            <option id="40">Madanapalle</option>
                                            <option id="164">Madgaon</option>
                                            <option id="129">Madhubani</option>
                                            <option id="888">Madhyamgram</option>
                                            <option id="648">Madurai</option>
                                            <option id="972">Maharajganj</option>
                                            <option id="41">Mahbubnagar</option>
                                            <option id="889">Maheshtala</option>
                                            <option id="767">Mahoba</option>
                                            <option id="202">Mahuva</option>
                                            <option id="768">Mainpuri</option>
                                            <option id="597">Makrana</option>
                                            <option id="360">Malappuram</option>
                                            <option id="890">Malbazar</option>
                                            <option id="465">Malegaon</option>
                                            <option id="551">Malerkotla</option>
                                            <option id="965">Malkangiri</option>
                                            <option id="466">Malkapur</option>
                                            <option id="552">Malout</option>
                                            <option id="263">Manali</option>
                                            <option id="42">Mancherial</option>
                                            <option id="43">Mandamarri</option>
                                            <option id="936">Mandi</option>
                                            <option id="247">MandiDabwali</option>
                                            <option id="553">MandiGobindgarh</option>
                                            <option id="400">Mandla</option>
                                            <option id="401">Mandsaur</option>
                                            <option id="203">Mandvi</option>
                                            <option id="329">Mandya</option>
                                            <option id="44">Mangalagiri</option>
                                            <option id="960">Mangaldai</option>
                                            <option id="330">Mangalore</option>
                                            <option id="204">Mangrol</option>
                                            <option id="361">Manjeri</option>
                                            <option id="467">Manmad</option>
                                            <option id="649">Mannargudi</option>
                                            <option id="554">Mansa</option>
                                            <option id="45">Markapur</option>
                                            <option id="891">Mathabhanga</option>
                                            <option id="769">Mathura</option>
                                            <option id="770">Mau</option>
                                            <option id="771">Mauranipur</option>
                                            <option id="772">Mawana</option>
                                            <option id="650">Mayiladuthurai</option>
                                            <option id="773">Meerut</option>
                                            <option id="205">Mehsana</option>
                                            <option id="892">Mekliganj</option>
                                            <option id="893">Memari</option>
                                            <option id="651">Mettupalayam</option>
                                            <option id="652">Mettur</option>
                                            <option id="402">Mhow</option>
                                            <option id="894">Midnapore</option>
                                            <option id="468">Miraj</option>
                                            <option id="895">Mirik</option>
                                            <option id="46">Miryalguda</option>
                                            <option id="774">Mirzapur</option>
                                            <option id="206">Modasa</option>
                                            <option id="775">Modinagar</option>
                                            <option id="555">Moga</option>
                                            <option id="556">Mohali</option>
                                            <option id="130">Mokama</option>
                                            <option id="776">Moradabad</option>
                                            <option id="207">Morbi</option>
                                            <option id="403">Morena</option>
                                            <option id="165">Mormugoa</option>
                                            <option id="948">Moscow-Russia</option>
                                            <option id="131">Motihari</option>
                                            <option id="777">Mubarakpur</option>
                                            <option id="778">Mughalsarai</option>
                                            <option id="132">Munger</option>
                                            <option id="779">Muradnagar</option>
                                            <option id="896">Murshidabad</option>
                                            <option id="698">Mussoorie</option>
                                            <option id="780">Muzaffarnagar</option>
                                            <option id="133">Muzaffarpur</option>
                                            <option id="331">Mysore</option>
                                            <option id="897">Nabadwip</option>
                                            <option id="975">Nabarangpur</option>
                                            <option id="557">Nabha</option>
                                            <option id="981">Nadia</option>
                                            <option id="208">Nadiad</option>
                                            <option id="103">Nagaon</option>
                                            <option id="653">Nagapattinam</option>
                                            <option id="598">Nagaur</option>
                                            <option id="404">Nagda</option>
                                            <option id="654">Nagercoil</option>
                                            <option id="781">Nagina</option>
                                            <option id="470">Nagpur</option>
                                            <option id="953">Nahan</option>
                                            <option id="898">Naihati</option>
                                            <option id="699">Nainital</option>
                                            <option id="782">Najibabad</option>
                                            <option id="47">Nalgonda</option>
                                            <option id="899">Nalhati</option>
                                            <option id="655">Namakkal</option>
                                            <option id="471">Nanded</option>
                                            <option id="472">Nandurbar</option>
                                            <option id="48">Nandyal</option>
                                            <option id="49">Narasaraopet</option>
                                            <option id="248">Narnaul</option>
                                            <option id="50">Narsapur</option>
                                            <option id="405">Narsinghpur</option>
                                            <option id="249">Narwana</option>
                                            <option id="473">Nashik</option>
                                            <option id="474">NavgharManikpur</option>
                                            <option id="475">Navi Mumbai</option>
                                            <option id="209">Navsari</option>
                                            <option id="783">Nawabganj</option>
                                            <option id="134">Nawada</option>
                                            <option id="599">Nawalgarh</option>
                                            <option id="955">Nawanshahr</option>
                                            <option id="362">Nedumangad</option>
                                            <option id="51">Nellore</option>
                                            <option id="900">New Barrackpur</option>
                                            <option id="928">New Jersey-USA</option>
                                            <option id="947">New York-USA</option>
                                            <option id="656">Neyveli</option>
                                            <option id="363">Neyyattinkara</option>
                                            <option id="406">Nimach</option>
                                            <option id="600">Nimbahera</option>
                                            <option id="332">Nipani</option>
                                            <option id="52">Nirmal</option>
                                            <option id="53">Nizamabad</option>
                                            <option id="104">NorthLakhimpur</option>
                                            <option id="951">Nuh</option>
                                            <option id="54">Nuzvid</option>
                                            <option id="785">Obra</option>
                                            <option id="55">Ongole</option>
                                            <option id="943">Ontario-Canada</option>
                                            <option id="657">Ooty</option>
                                            <option id="786">Orai</option>
                                            <option id="476">Osmanabad</option>
                                            <option id="532">Ozhukarai</option>
                                            <option id="987">Padrauna</option>
                                            <option id="364">Palakkad</option>
                                            <option id="56">Palakol</option>
                                            <option id="658">Palani</option>
                                            <option id="210">Palanpur</option>
                                            <option id="477">Palghar</option>
                                            <option id="601">Pali</option>
                                            <option id="211">Palitana</option>
                                            <option id="956">Pallahara</option>
                                            <option id="659">Pallavaram</option>
                                            <option id="250">Palwal</option>
                                            <option id="57">Palwancha</option>
                                            <option id="251">Panchkula</option>
                                            <option id="478">Pandharpur</option>
                                            <option id="901">Panihati</option>
                                            <option id="252">Panipat</option>
                                            <option id="977">Panjim</option>
                                            <option id="407">Panna</option>
                                            <option id="660">Panruti</option>
                                            <option id="902">Panskura</option>
                                            <option id="479">Panvel</option>
                                            <option id="525">Paradip</option>
                                            <option id="661">Paramakudi</option>
                                            <option id="408">Parasia</option>
                                            <option id="480">Parbhani</option>
                                            <option id="481">Parli</option>
                                            <option id="212">Patan</option>
                                            <option id="558">Pathankot</option>
                                            <option id="559">Patiala</option>
                                            <option id="135">Patna</option>
                                            <option id="662">Pattukkottai</option>
                                            <option id="365">Payyannur</option>
                                            <option id="213">Petlad</option>
                                            <option id="560">Phagwara</option>
                                            <option id="482">Phaltan</option>
                                            <option id="136">PhulwariSharif</option>
                                            <option id="290">Phusro</option>
                                            <option id="787">Pilibhit</option>
                                            <option id="788">Pilkhuwa</option>
                                            <option id="483">PimpriChinchwad</option>
                                            <option id="58">Pitapuram</option>
                                            <option id="409">Pithampur</option>
                                            <option id="663">Pollachi</option>
                                            <option id="533">Pondicherry</option>
                                            <option id="366">Ponnani</option>
                                            <option id="59">Ponnur</option>
                                            <option id="214">Porbandar</option>
                                            <option id="1">Port Blair</option>
                                            <option id="60">Proddatur</option>
                                            <option id="664">Pudukkottai</option>
                                            <option id="903">Pujali</option>
                                            <option id="665">Puliyankudi</option>
                                            <option id="484">Pune</option>
                                            <option id="526">Puri</option>
                                            <option id="137">Purnia</option>
                                            <option id="904">Purulia</option>
                                            <option id="485">Pusad</option>
                                            <option id="602">Pushkar</option>
                                            <option id="61">Qutubullapur</option>
                                            <option id="333">RabkaviBanhatti</option>
                                            <option id="789">Raebareli</option>
                                            <option id="905">Raghunathpur</option>
                                            <option id="334">Raichur</option>
                                            <option id="486">Raigad</option>
                                            <option id="906">Raiganj</option>
                                            <option id="156">Raigarh</option>
                                            <option id="157">Raipur</option>
                                            <option id="62">Rajahmundry</option>
                                            <option id="666">Rajapalayam</option>
                                            <option id="63">Rajendranagar</option>
                                            <option id="603">Rajgarh</option>
                                            <option id="215">Rajkot</option>
                                            <option id="158">RajNandgaon</option>
                                            <option id="561">Rajpura</option>
                                            <option id="907">RajpurSonarpur</option>
                                            <option id="604">Rajsamand</option>
                                            <option id="64">Ramachandrapuram</option>
                                            <option id="65">Ramagundam</option>
                                            <option id="335">Ramanagaram</option>
                                            <option id="667">Ramanathapuram</option>
                                            <option id="291">Ramgarh</option>
                                            <option id="790">Rampur</option>
                                            <option id="908">Rampurhat</option>
                                            <option id="909">Ranaghat</option>
                                            <option id="292">Ranchi</option>
                                            <option id="336">Ranebennur</option>
                                            <option id="910">Raniganj</option>
                                            <option id="216">Ranip</option>
                                            <option id="605">Ratangarh</option>
                                            <option id="791">Rath</option>
                                            <option id="410">Ratlam</option>
                                            <option id="487">Ratnagiri</option>
                                            <option id="66">Rayachoti</option>
                                            <option id="67">Rayadurg</option>
                                            <option id="527">Rayagada</option>
                                            <option id="792">Renukoot</option>
                                            <option id="411">Rewa</option>
                                            <option id="253">Rewari</option>
                                            <option id="700">Rishikesh</option>
                                            <option id="911">Rishra</option>
                                            <option id="337">Robertsonpet</option>
                                            <option id="254">Rohtak</option>
                                            <option id="701">Roorkee</option>
                                            <option id="966">Ropar</option>
                                            <option id="528">Rourkela</option>
                                            <option id="983">Rudraprayag</option>
                                            <option id="702">Rudrapur</option>
                                            <option id="412">Sagar</option>
                                            <option id="338">Sagara</option>
                                            <option id="793">Saharanpur</option>
                                            <option id="138">Saharsa</option>
                                            <option id="794">Sahaswan</option>
                                            <option id="293">Sahebganj</option>
                                            <option id="950">Sahibabad</option>
                                            <option id="912">Sainthia</option>
                                            <option id="668">Salem</option>
                                            <option id="68">Samalkota</option>
                                            <option id="139">Samastipur</option>
                                            <option id="529">Sambalpur</option>
                                            <option id="795">Sambhal</option>
                                            <option id="488">Sangamner</option>
                                            <option id="69">Sangareddy</option>
                                            <option id="489">Sangli</option>
                                            <option id="562">Sangrur</option>
                                            <option id="669">Sankarankoil</option>
                                            <option id="606">Sardarshahar</option>
                                            <option id="413">Sarni</option>
                                            <option id="140">Sasaram</option>
                                            <option id="490">Satara</option>
                                            <option id="414">Satna</option>
                                            <option id="70">Sattenapalle</option>
                                            <option id="294">Saunda</option>
                                            <option id="217">Savarkundla</option>
                                            <option id="607">SawaiMadhopur</option>
                                            <option id="71">Secunderabad</option>
                                            <option id="415">Sehore</option>
                                            <option id="416">Seoni</option>
                                            <option id="913">Serampore</option>
                                            <option id="72">Serilingampally</option>
                                            <option id="796">Shahabad</option>
                                            <option id="417">Shahdol</option>
                                            <option id="797">Shahjahanpur</option>
                                            <option id="418">Shajapur</option>
                                            <option id="798">Shamli</option>
                                            <option id="914">Shantipur</option>
                                            <option id="491">Shegaon</option>
                                            <option id="419">Sheopur</option>
                                            <option id="799">Sherkot</option>
                                            <option id="800">Shikohabad</option>
                                            <option id="504">Shillong</option>
                                            <option id="264">Shimla</option>
                                            <option id="339">Shimoga</option>
                                            <option id="492">Shirpur</option>
                                            <option id="420">Shivpuri</option>
                                            <option id="493">Shrirampur</option>
                                            <option id="73">Siddipet</option>
                                            <option id="218">Sidhpur</option>
                                            <option id="801">Sikandrabad</option>
                                            <option id="608">Sikar</option>
                                            <option id="105">Silchar</option>
                                            <option id="915">Siliguri</option>
                                            <option id="159">Silvassa</option>
                                            <option id="340">Sindhnur</option>
                                            <option id="295">Sindri</option>
                                            <option id="421">Singrauli</option>
                                            <option id="341">Sira</option>
                                            <option id="563">Sirhind</option>
                                            <option id="957">Sirohi</option>
                                            <option id="255">Sirsa</option>
                                            <option id="342">Sirsi</option>
                                            <option id="74">Sirsilla</option>
                                            <option id="141">Sitamarhi</option>
                                            <option id="802">Sitapur</option>
                                            <option id="670">Sivakasi</option>
                                            <option id="106">Sivasagar</option>
                                            <option id="973">Siwan</option>
                                            <option id="938">Solan</option>
                                            <option id="494">Solapur</option>
                                            <option id="916">Sonamukhi</option>
                                            <option id="962">Sonepur</option>
                                            <option id="256">Sonipat</option>
                                            <option id="270">Sopore</option>
                                            <option id="75">Srikakulam</option>
                                            <option id="76">Srikalahasti</option>
                                            <option id="564">SriMuktsarSahib</option>
                                            <option id="271">Srinagar</option>
                                            <option id="671">Srivilliputhur</option>
                                            <option id="609">Sujangarh</option>
                                            <option id="803">Sultanpur</option>
                                            <option id="530">Sunabeda</option>
                                            <option id="565">Sunam</option>
                                            <option id="142">Supaul</option>
                                            <option id="963">Surajpur</option>
                                            <option id="219">Surat</option>
                                            <option id="610">Suratgarh</option>
                                            <option id="220">Surendranagar</option>
                                            <option id="917">Suri</option>
                                            <option id="77">Suryapet</option>
                                            <option id="78">Tadepalligudem</option>
                                            <option id="79">Tadpatri</option>
                                            <option id="918">Taherpur</option>
                                            <option id="919">Taki</option>
                                            <option id="367">Taliparamba</option>
                                            <option id="920">Tamluk</option>
                                            <option id="804">Tanda</option>
                                            <option id="80">Tandur</option>
                                            <option id="81">Tanuku</option>
                                            <option id="921">Tarakeswar</option>
                                            <option id="566">TarnTaranSahib</option>
                                            <option id="82">Tenali</option>
                                            <option id="672">Tenkasi</option>
                                            <option id="107">Tezpur</option>
                                            <option id="368">Thalassery</option>
                                            <option id="495">Thane</option>
                                            <option id="257">Thanesar</option>
                                            <option id="673">Thanjavur</option>
                                            <option id="674">TheniAllinagaram</option>
                                            <option id="675">Thiruvarur</option>
                                            <option id="676">Thoothukudi</option>
                                            <option id="369">Thrissur</option>
                                            <option id="970">Tijara</option>
                                            <option id="422">Tikamgarh</option>
                                            <option id="805">Tilhar</option>
                                            <option id="677">Tindivanam</option>
                                            <option id="108">Tinsukia</option>
                                            <option id="343">Tiptur</option>
                                            <option id="678">Tiruchendur</option>
                                            <option id="679">Tiruchengode</option>
                                            <option id="680">Tirunelveli</option>
                                            <option id="681">Tirupathur</option>
                                            <option id="83">Tirupati</option>
                                            <option id="682">Tirupur</option>
                                            <option id="370">Tirur</option>
                                            <option id="371">Tiruvalla</option>
                                            <option id="683">Tiruvannamalai</option>
                                            <option id="296">Tisra</option>
                                            <option id="922">Titagarh</option>
                                            <option id="258">Tohana</option>
                                            <option id="611">Tonk</option>
                                            <option id="942">Toronto-Canada</option>
                                            <option id="684">Trichy</option>
                                            <option id="372">Trivandrum</option>
                                            <option id="923">Tufanganj</option>
                                            <option id="344">Tumkur</option>
                                            <option id="806">Tundla</option>
                                            <option id="84">Tuni</option>
                                            <option id="505">Tura</option>
                                            <option id="612">Udaipur</option>
                                            <option id="988">Udaipura</option>
                                            <option id="496">Udgir</option>
                                            <option id="272">Udhampur</option>
                                            <option id="685">Udumalaipettai</option>
                                            <option id="345">Udupi</option>
                                            <option id="807">Ujhani</option>
                                            <option id="423">Ujjain</option>
                                            <option id="924">Uluberia</option>
                                            <option id="221">Una-Gujarat</option>
                                            <option id="993">Una-Himachal</option>
                                            <option id="222">Unjha</option>
                                            <option id="808">Unnao</option>
                                            <option id="223">Upleta</option>
                                            <option id="85">Uppal</option>
                                            <option id="497">UranIslampur</option>
                                            <option id="949">USA</option>
                                            <option id="925">Uttarpara</option>
                                            <option id="224">Vadodara</option>
                                            <option id="935">Vaikom</option>
                                            <option id="686">Valparai</option>
                                            <option id="225">Valsad</option>
                                            <option id="687">Vaniyambadi</option>
                                            <option id="226">Vapi</option>
                                            <option id="809">Varanasi</option>
                                            <option id="498">VasaiVirar</option>
                                            <option id="227">Vejalpur</option>
                                            <option id="688">Vellore</option>
                                            <option id="228">Veraval</option>
                                            <option id="424">Vidisha</option>
                                            <option id="229">Vijalpor</option>
                                            <option id="86">Vijayawada</option>
                                            <option id="689">Viluppuram</option>
                                            <option id="87">Vinukonda</option>
                                            <option id="230">Viramgam</option>
                                            <option id="690">Virudhachalam</option>
                                            <option id="691">Virudhunagar</option>
                                            <option id="939">Visakhapatnam</option>
                                            <option id="231">Visnagar</option>
                                            <option id="88">Vizag</option>
                                            <option id="89">Vizianagaram</option>
                                            <option id="810">Vrindavan</option>
                                            <option id="90">Wanaparthi</option>
                                            <option id="499">Wani</option>
                                            <option id="91">Warangal</option>
                                            <option id="500">Wardha</option>
                                            <option id="501">Washim</option>
                                            <option id="945">Wayanad</option>
                                            <option id="346">Yadgir</option>
                                            <option id="259">Yamunanagar</option>
                                            <option id="502">Yavatmal</option>
                                            <option id="92">Yemmiganur</option>
                                            <option id="969">Zirakpur</option>
                                        </select>
                                    </div>
                                    <div class="col-md-12 form-group">
                                        <label>Subject</label>
                                        <input type="text" name="subject" maxlength="70"
                                               placeholder="Limit 70 characters"
                                               class="form-control" required>
                                    </div>
                                    <div class="col-md-12 form-group">
                                        <label>Question</label>
                                        <textarea name="question" maxlength="1000"
                                                  placeholder="Limit 1000 characters" class="form-control"
                                                  rows="10"></textarea>
                                    </div>
                                    <div class="col-md-12 form-group">
                                        <h3>Your Contact Detail</h3>
                                        <label>Name</label>
                                        <input type="text" name="name" maxlength="50" placeholder="Your Name"
                                               class="form-control" required>
                                    </div>
                                    <div class="col-md-12 form-group">
                                        <label>Email</label>
                                        <input type="text" name="email" maxlength="50" placeholder="Your Email"
                                               class="form-control" required>
                                    </div>
                                    <div class="col-md-12 form-group">
                                        <label>Contact Number</label>
                                        <input type="text" maxlength="16" name="number"
                                               placeholder="Your contact number" class="form-control" required>
                                    </div>
                                    <div class="col-md-12 form-group">
                                        <button type="submit" class="btn btn-lg btn-danger">Submit</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>
@endsection



